nameSpace: stars
ingressNamespace: ingress-nginx
studentAppName: moviestar
videoEditorAppName: videomerge
studentHostName: moviestar
videoEditorHostName: video-editor
studentAppPort: 80
videoEditorAppPort: 5000
studentVersion: 5
videoEditorVersion: 2


branch: master
